### PR TITLE
admins should get to create accounts for others

### PR DESCRIPTION
**Pull request by Radical-from-Scratch**

### CODE REVIEW

**Comment by Radical-from-Scratch** [comment]
Could somebody please review this? It will literally take 2 seconds!

**Comment by bjskistad** [comment]
I don't know enough PHP. Better ask robin.

**Comment by Radical-from-Scratch** [comment]
@robinp7728

**Comment by Radical-from-Scratch** [comment]
I'm going to merge it because it was copied off of FluxBB's own code. I will ask rob for the next one tho

**Comment by bjskistad** [comment]
Kay.

**Comment by Radical-from-Scratch** [comment]
I pinged robin o. Gitter about my other pull.

**Pull request merged**
